# Generated by Django 3.2.25 on 2026-05-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nivo_aktivnosti',
            new_name='razina_aktivnosti',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='pol',
            new_name='spol',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cilj',
            field=models.CharField(blank=True, choices=[('loss', 'Weight loss (mršavljenje)'), ('maintain', 'Maintenance (održavanje)'), ('bulk', 'Bulk (dobivanje mase)')], max_length=15, null=True),
        ),
    ]
