# Generated by Django 3.2.25 on 2026-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260512_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilna_slika',
            field=models.ImageField(blank=True, default='profilne_slike/default_avatar.png', null=True, upload_to='profilne_slike/'),
        ),
    ]
