# Generated by Django 3.2.25 on 2026-05-19 09:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namirnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('kalorije', models.PositiveIntegerField(default=0, help_text='Kalorije na 100g')),
                ('proteini', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('ugljikohidrati', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('masti', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Namirnice',
            },
        ),
        migrations.CreateModel(
            name='Obrok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('kategorija', models.CharField(choices=[('Doručak', 'Doručak'), ('Ručak', 'Ručak'), ('Večera', 'Večera'), ('Međuobrok', 'Međuobrok')], max_length=50)),
                ('recept', models.TextField(blank=True, null=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='obroci/')),
            ],
            options={
                'verbose_name_plural': 'Obroci',
            },
        ),
        migrations.CreateModel(
            name='StavkaObroka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramaza', models.PositiveIntegerField(default=100)),
                ('namirnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.namirnica')),
                ('obrok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='nutrition.obrok')),
            ],
        ),
        migrations.CreateModel(
            name='PlanIshrane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciljne_kalorije', models.PositiveIntegerField(default=2000)),
                ('ciljni_proteini', models.PositiveIntegerField(default=150)),
                ('ciljni_ugljikohidrati', models.PositiveIntegerField(default=200)),
                ('ciljne_masti', models.PositiveIntegerField(default=70)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planishrane', to=settings.AUTH_USER_MODEL)),
                ('obroci', models.ManyToManyField(blank=True, to='nutrition.Obrok')),
            ],
            options={
                'verbose_name_plural': 'Planovi Ishrane',
            },
        ),
    ]
