# Generated by Django 3.2.25 on 2026-05-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planishrane',
            name='broj_generiranja',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
