# Generated by Django 3.2.25 on 2026-05-12 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanTreninga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Npr. DAN 1 - Prsa + Srednje rame', max_length=100)),
                ('redni_broj', models.PositiveIntegerField(help_text='Za redoslijed prikaza (1, 2, 3...)')),
            ],
            options={
                'ordering': ['redni_broj'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Npr. Trening za muškarce 12 tjedana', max_length=100)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vjezba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Npr. 1. KOSI BENCH PRESS', max_length=100)),
                ('video_url', models.URLField(blank=True, help_text='Link na video s izvođenjem', null=True)),
                ('upute', models.TextField(blank=True, help_text='Npr. Zagrijavanje 15 pon, Radne 12 pon...', null=True)),
                ('redni_broj', models.PositiveIntegerField()),
                ('dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vjezbe', to='workouts.dantreninga')),
            ],
            options={
                'ordering': ['redni_broj'],
            },
        ),
        migrations.CreateModel(
            name='OdradenaSerija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('broj_serije', models.PositiveIntegerField(help_text='Npr. 1, 2, 3...')),
                ('ponavljanja', models.PositiveIntegerField()),
                ('tezina', models.DecimalField(decimal_places=2, help_text='Kilaža u kg', max_digits=5)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='povijest_treninga', to=settings.AUTH_USER_MODEL)),
                ('vjezba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odradene_serije', to='workouts.vjezba')),
            ],
            options={
                'ordering': ['-datum', 'broj_serije'],
            },
        ),
        migrations.AddField(
            model_name='dantreninga',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dani', to='workouts.program'),
        ),
    ]
