# Generated by Django 3.2.25 on 2026-05-15 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dantreninga',
            options={},
        ),
        migrations.AlterModelOptions(
            name='odradenaserija',
            options={},
        ),
        migrations.RemoveField(
            model_name='dantreninga',
            name='redni_broj',
        ),
        migrations.RemoveField(
            model_name='odradenaserija',
            name='datum',
        ),
        migrations.AddField(
            model_name='odradenaserija',
            name='je_pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dantreninga',
            name='naziv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='odradenaserija',
            name='broj_serije',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='odradenaserija',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odradenaserija',
            name='tezina',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='naziv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='opis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='naziv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='upute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TreningSesija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocetak', models.DateTimeField(default=django.utils.timezone.now)),
                ('kraj', models.DateTimeField(blank=True, null=True)),
                ('aktivan', models.BooleanField(default=True)),
                ('ukupni_volumen', models.FloatField(default=0.0)),
                ('dan_treninga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.dantreninga')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesije_treninga', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='odradenaserija',
            name='sesija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serije', to='workouts.treningsesija'),
        ),
    ]
