# Generated by Django 3.2.25 on 2026-05-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_auto_20260515_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odradenaserija',
            options={'ordering': ['broj_serije']},
        ),
        migrations.RemoveField(
            model_name='odradenaserija',
            name='korisnik',
        ),
        migrations.RemoveField(
            model_name='treningsesija',
            name='aktivan',
        ),
        migrations.RemoveField(
            model_name='treningsesija',
            name='ukupni_volumen',
        ),
        migrations.RemoveField(
            model_name='vjezba',
            name='video_url',
        ),
        migrations.AddField(
            model_name='program',
            name='kreator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moji_programi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treningsesija',
            name='zavrseno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vjezba',
            name='video_fajl',
            field=models.FileField(blank=True, null=True, upload_to='vjezbe_videa/'),
        ),
        migrations.AlterField(
            model_name='odradenaserija',
            name='sesija',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serije', to='workouts.treningsesija'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='odradenaserija',
            name='tezina',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='odradenaserija',
            name='vjezba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.vjezba'),
        ),
        migrations.AlterField(
            model_name='program',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treningsesija',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treningsesija',
            name='pocetak',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
