# Generated by Django 3.2.25 on 2026-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20260518_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatalogVjezbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('upute', models.TextField(blank=True, null=True)),
                ('video_fajl', models.FileField(blank=True, null=True, upload_to='vjezbe_videa/')),
            ],
            options={
                'verbose_name_plural': 'Katalog Vježbi',
                'ordering': ['naziv'],
            },
        ),
    ]
