# Generated by Django 3.2.25 on 2026-05-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_katalogvjezbi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalogvjezbi',
            name='upute',
        ),
        migrations.RemoveField(
            model_name='vjezba',
            name='upute',
        ),
        migrations.AddField(
            model_name='odradenaserija',
            name='rpe',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
