# Generated by Django 3.2.25 on 2026-05-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20260518_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katalogvjezbi',
            options={'ordering': ['kategorija', 'naziv'], 'verbose_name_plural': 'Katalog Vježbi'},
        ),
        migrations.AddField(
            model_name='katalogvjezbi',
            name='kategorija',
            field=models.CharField(choices=[('Prsa', 'Prsa'), ('Leđa', 'Leđa'), ('Noge', 'Noge'), ('Ramena', 'Ramena'), ('Ruke', 'Ruke'), ('Core', 'Core'), ('Cardio', 'Cardio')], default='Prsa', max_length=50),
        ),
    ]
