# Generated by Django 3.2.25 on 2026-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20260518_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vjezba',
            name='video_fajl',
        ),
        migrations.AddField(
            model_name='vjezba',
            name='video',
            field=models.FileField(blank=True, help_text='Kratki MP4 video (do 10 sekundi, max 5MB)', null=True, upload_to='vjezbe_videi/'),
        ),
    ]
