# Generated by Django 3.2.25 on 2026-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20260520_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalogvjezbi',
            name='video_fajl',
        ),
        migrations.AddField(
            model_name='katalogvjezbi',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vjezbe_videi/'),
        ),
    ]
